name: 'Vulnerability Scanner Action'
description: 'Scan repository for security vulnerabilities'
author: 'wai'

inputs:
  severity-level:
    description: 'Minimum severity level to report'
    required: true
    default: 'medium'
  scan-directory:
    description: 'Directory to scan'
    required: true
    default: '.'
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  perplexity-api-key:
    description: 'Perplexity Sonar API key'
    required: true
  gemini-api-key:
    description: 'Gemini API key'
    required: true

outputs:
  result:
    description: 'Scan result summary'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'green' 