name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: read
  checks: write
  statuses: write

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Security Check
        uses: zahmis/vuln-scan-action@v1.0.14
        with:
          severity-level: 'medium'
          scan-directory: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }} 