name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Security Check
        uses: zahmis/vuln-scan-action@v1.0.5
        with:
          severity-level: 'medium'
          scan-directory: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }} 