name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Security Check
        uses: zahmis/vuln-scan-action@v1.0.8
        with:
          severity-level: 'medium'
          scan-directory: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }} 