name: セキュリティスキャン

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 脆弱性スキャンを実行
        uses: zahmis/vuln-scan-action@v1.0.25
        with:
          severity-level: 'high'
          scan-directory: '.'
          perplexity-api-key: ${{ secrets.PERPLEXITY_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write
  pull-requests: write 