name: セキュリティスキャン

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write 

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 脆弱性スキャンを実行
        uses: zahmis/vuln-scan-action@v1.0.34
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          perplexity-api-key: ${{ secrets.PERPLEXITY_API_KEY }}
          severity-level: medium
          scan-directory: '.' 