name: セキュリティスキャン

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 脆弱性スキャンを実行
        uses: zahmis/vuln-scan-action@v1.0.23
        with:
          severity-level: 'high'
          scan-directory: '.'
          perplexity-api-key: ${{ secrets.PERPLEXITY_API_KEY }}
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }} 